### ISSUE TITLE
builder is not defined

### ISSUE THREAD

**Issue by alexbeletsky** [sindresorhus/time-grunt#66]
I'm having very strange error, that appeared after `angular-ui-grid` being installed to the project. It sounds totally unrelated, but now when I run `grunt build:dev`, I have such error,

```bash
Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/time-grunt/node_modules/chalk/index.js:40
		return applyStyle.apply(builder, arguments);
		                        ^
ReferenceError: builder is not defined
    at Chalk.builder (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/time-grunt/node_modules/chalk/index.js:40:27)
    at process.<anonymous> (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/time-grunt/index.js:155:22)
    at process.g (events.js:199:16)
    at process.emit (events.js:107:17)
    at process.exit (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/time-grunt/index.js:41:11)
    at tryToExit (/Users/alexanderbeletsky/Development/Projects/mylorry/shift-planner-office/node_modules/grunt/node_modules/exit/lib/exit.js:17:15)
```

It's from `chalk` library, 

```js
function build(_styles) {
	var builder = function builder() {
		return applyStyle.apply(builder, arguments);
	};

	builder._styles = _styles;
	builder.enabled = this.enabled;
	// __proto__ is used because we must return a function, but there is
	// no way to create a function with a different prototype.
	/*eslint no-proto: 0 */
	builder.__proto__ = proto;

	return builder;
}
```

Which looks like a valid code. Any pointers will be appreciated.

```
› node --version
v0.12.5
› npm --version
2.11.2
```

PS. I'm using time-grunt, chalk in other projects and never seen anything like that.

[Gruntfile.js](https://gist.github.com/alexbeletsky/3938fe99ca9de52f4384)

**Comment by sindresorhus** [comment]
Closing in favor of https://github.com/chalk/chalk/issues/80.
