### ISSUE TITLE
TypeError: chalk.stripColor is not a function

### ISSUE THREAD

**Issue by bcherny** [sindresorhus/time-grunt#77]
```
Execution Time (2016-03-28 23:56:07 UTC)
/Users/bcherny/foo/node_modules/time-grunt/index.js:140
        return chalk.stripColor(str).length;
                     ^

TypeError: chalk.stripColor is not a function
    at table.stringLength (/Users/bcherny/foo/node_modules/time-grunt/index.js:140:18)
    at /Users/bcherny/foo/node_modules/text-table/index.js:33:21
    at Array.forEach (native)
    at forEach (/Users/bcherny/foo/node_modules/text-table/index.js:73:31)
    at /Users/bcherny/foo/node_modules/text-table/index.js:32:9
    at Array.reduce (native)
    at reduce (/Users/bcherny/foo/node_modules/text-table/index.js:63:30)
    at module.exports (/Users/bcherny/foo/node_modules/text-table/index.js:31:17)
    at formatTable (/Users/bcherny/foo/node_modules/time-grunt/index.js:137:10)
    at process.<anonymous> (/Users/bcherny/foo/node_modules/time-grunt/index.js:163:7)
```

**Comment by sindresorhus** [comment]
https://github.com/chalk/chalk/issues/106
